### ISSUE TITLE
catkin_make error (DUtils/DUtils.h is missing)

### ISSUE THREAD

**Issue by amiltonwong** [alejocb/rgbdtam#1]
Hi, @alejocb ,

I followed the steps in readme. However, it encounters catkin_make error as follows:
```
                 from /root/catkin_ws/src/rgbdtam/src/vo_system.cpp:21:
/root/catkin_ws/src/rgbdtam/ThirdParty/DBoW2/DBoW2/TemplatedDatabase.h:27:27: fatal error: DUtils/DUtils.h: No such file or directory
 #include "DUtils/DUtils.h"
                           ^
compilation terminated.

```
It seems DUtils/DUtils.h is missing
log [details](https://gist.github.com/amiltonwong/c61b1c985a1d602db28979709ab7b60b).

Any suggestion to fix it?

Thanks~

**Comment by alejocb** [comment]
Hi @amiltonwong ,

Thank you for your feedback. I did not test the code in other computers yet and I can't do it now, I will test it next Wednesday and I will try to fix this issue also. If I remember well I had to install this repository (https://github.com/dorian3d/DLib)  in my system, but not sure.

Best,
Alejo.

**Comment by alejocb** [comment]
Hi @amiltonwong ,

 I fixed this issue, it should work now... if you have any other problem I will appreciate your feedback.

Thanks
