### ISSUE TITLE
loading too much during catkin_make

### ISSUE THREAD

**Issue by nurimertvural** [alejocb/rgbdtam#5]
Hi,
When I try to compile the package, my pc get slower since the processor is loaded too much. I do not know if it is because the package itself or there is a lack of dependency on my computer. During compiling on the screen:
[ 12%] [ 25%] [ 37%] [ 50%] Building CXX object rgbdtam/CMakeFiles/rgbdtam.dir/src/SemiDenseMapping.cpp.o
Building CXX object rgbdtam/CMakeFiles/rgbdtam.dir/src/SemiDenseTracking.cpp.o
Building CXX object rgbdtam/CMakeFiles/rgbdtam.dir/src/DenseMapping.cpp.o
Building CXX object rgbdtam/CMakeFiles/rgbdtam.dir/src/vo_system.cpp.o

and do not process further. Any suggestion?
Thanks

**Comment by alejocb** [comment]
Hi @nmv45,

This is because your computer is using all possible cores to compile the code. Try this command so that it only uses 3 cores:

    catkin_make rgbdtam -j3

I updated the readme to avoid this problem.
